version: '1'
services:
  app:
    image: storeapi
    ports:
     - 9090:8080
    environment:
     - MYSQL_HOST=mysql
     - MYSQL_USER=root
     - MYSQL_PASSWORD=root
     - MYSQL_PORT=3306
    depends_on:
      - mysql
    command: ["./wait-for-it.sh", "db:5432", "--", "python", "app.py"]

  mysql:
    image: mysql
    ports:
     - 3307:3306
    environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_DATABASE=root
