version: '3'
services:
  app:
    container_name: app
    image: storeapi
    ports:
     - 9090:8080
    environment:
     - MYSQL_HOST=db
     - MYSQL_USER=root
     - MYSQL_PASSWORD=root
     - MYSQL_PORT=3306
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: db
    image: mysql
    ports:
     - 3307:3306
    environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_DATABASE=root
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
